AWSTemplateFormatVersion: "2010-09-09"
Description:  This template creates a secret which stores the received parameter.
Parameters:
  BitriseControllerToken:
    Description: Please provide the token you received at Controller creation.
    Type: String
    AllowedPattern: .+
    NoEcho: true
  BitriseWorkspaceID:
    Description: Please provide your Bitrise Workspace ID.
    Type: String
    AllowedPattern: .+
Resources:
  ControllerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Stores the Bitrise Controller token"
      Name: bitrise-controller-token
      SecretString: !Ref BitriseControllerToken
      Tags: 
        - Key: managed-by-bitrise
          Value: "true"
  WorkspaceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Stores the Bitrise WorkspaceID"
      Name: bitrise-workspace-id
      SecretString: !Ref BitriseWorkspaceID
      Tags: 
        - Key: managed-by-bitrise
          Value: "true"
Outputs:
  ControllerSecretArn:
    Description: A reference to the managed Bitrise Controller secret
    Value: !Ref ControllerSecret
    Export:
      Name: BitriseControllerTokenSecretArn
  WorkspaceSecretArn:
    Description: A reference to the managed Bitrise WorkplaceID secret
    Value: !Ref WorkspaceSecret
    Export:
      Name: BitriseWorkplaceIDSecretArn
