AWSTemplateFormatVersion: "2010-09-09"
Description:  This template creates an empty Instance Role which is attached to the VM by default.

Parameters:
  BitriseWorkspaceID:
    Description: Please provide your Bitrise Workspace ID.
    Type: String
    AllowedPattern: .+

Resources:
  BitriseAgentDefaultEC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies: []
      RoleName: !Sub ${BitriseWorkspaceID}-bitrise-agent-default-role
      Tags:
        - Key: managed-by-bitrise
          Value: "true"
  BitriseAgentDefaultInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${BitriseWorkspaceID}-bitrise-agent-default-instance-profile
      Path: /
      Roles:
        - Ref: BitriseAgentDefaultEC2Role

Outputs: {}
